/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertError: typeof import('./resources/js/components/AlertError.vue')['default']
    AppLogo: typeof import('./resources/js/components/AppLogo.vue')['default']
    AppLogoIcon: typeof import('./resources/js/components/AppLogoIcon.vue')['default']
    AuthCard: typeof import('./resources/js/components/AuthCard.vue')['default']
    Avatar: typeof import('./resources/js/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./resources/js/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./resources/js/components/ui/avatar/AvatarImage.vue')['default']
    Badge: typeof import('./resources/js/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./resources/js/components/ui/button/Button.vue')['default']
    Card: typeof import('./resources/js/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./resources/js/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./resources/js/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./resources/js/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./resources/js/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./resources/js/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./resources/js/components/ui/checkbox/Checkbox.vue')['default']
    DeleteAccount: typeof import('./resources/js/components/DeleteAccount.vue')['default']
    Dialog: typeof import('./resources/js/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./resources/js/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./resources/js/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./resources/js/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./resources/js/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./resources/js/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./resources/js/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./resources/js/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./resources/js/components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./resources/js/components/ui/input/Input.vue')['default']
    Label: typeof import('./resources/js/components/ui/label/Label.vue')['default']
    Separator: typeof import('./resources/js/components/ui/separator/Separator.vue')['default']
    SettingsMembersList: typeof import('./resources/js/components/settings/SettingsMembersList.vue')['default']
    Textarea: typeof import('./resources/js/components/ui/textarea/Textarea.vue')['default']
    TextLink: typeof import('./resources/js/components/TextLink.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/inertia/components/Link.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UserMenu: typeof import('./resources/js/components/UserMenu.vue')['default']
  }
}
